# version of docker engine
version: "3.5"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mariadb:
    driver: ${VOLUMES_DRIVER}
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}
  adminer:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:
  #=== App ===#
  app:
    build:
      context: ./php-fpm
    container_name: ${APP_NAME}
    volumes:
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    networks:
      - backend
  #=== Nginx ===#
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    container_name: ${APP_NAME}_nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    restart: unless-stopped
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - app
    networks:
      - backend
  # #=== Mariadb ===#
  mariadb:
    build:
      context: ./mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - MARIADB_VERSION=${MARIADB_VERSION}
    container_name: ${APP_NAME}_mariadb
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - TZ=${APP_TIMEZONE}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - backend
  # #=== Adminer ===#
  adminer:
    build:
      context: ./adminer
      args:
        - INSTALL_MSSQL=${ADM_INSTALL_MSSQL}
    environment:
        - ADMINER_PLUGINS=${ADM_PLUGINS}
        - ADMINER_DESIGN=${ADM_DESIGN}
        - ADMINER_DEFAULT_SERVER=${ADM_DEFAULT_SERVER}
    ports:
      - "${ADM_PORT}:8080"
    depends_on:
      - app
    networks:
      - backend
  # #=== Redis ===#
  # redis:
  #   build:
  #     context: ./redis
  #     args:
  #       - REDIS_VERSION=${REDIS_VERSION}
  #   volumes:
  #     - ${DATA_PATH_HOST}/redis:/data
  #   command: --requirepass ${REDIS_PASSWORD}
  #   ports:
  #     - "${REDIS_PORT}:6379"
  #   networks:
  #     - backend
  # #=== Mailhog ===#
  # mailhog:
  #   build: ./mailhog
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   networks:
  #     - backend
